### ISSUE TITLE
Suggestion: Load existing e-reader levels

### ISSUE THREAD

**Issue by mariomadproductions** [city41/smaghetti#51]
I think it would be useful in documenting object parameters if existing levels could be loaded - entities that aren't documented yet could use fallback graphics/settings boxes (e.g. just using a raw hex view rather than the "friendly" settings box)

**Comment by city41** [comment]
I have a tool that does that, you can try it here: https://smaghetti.com/tools/hex-tree

I recommend star02 to see the tool in action. Many e-reader levels just show a ton of question marks as their entities haven't been figured out yet.

![image](https://user-images.githubusercontent.com/141159/120485236-e4b1ff00-c381-11eb-8c06-86bb74e1b9dd.png)

**Comment by city41** [comment]
the problem with trying to load unknown entities into smaghetti itself is entities can be 4, 5 or 6 bytes in size and if you don't know their size, the whole level falls apart and it becomes a huge mess.

**Comment by mariomadproductions** [comment]
Ah I see. How do I extract a .level file? I've got the e-Card .raw file.

Also, I don't really understand the thing about the entity size. How does the game and hex tree cope with that? How come the main editor can't do the same thing they do?

**Comment by city41** [comment]
I *think* the .raw files are still encrypted? I'm not totally sure as I was able to get .level files. They do exist out there, but you'll have to find them on your own unfortunately.

as for entity size, the game copes with it because the game fully understands all entities. It knows if it encounters Goomba, that Goomba is 4 bytes, and if it encounters Charging Chuck, chuck is 5 bytes. Nintendo coded the game to fully understand all entities.

hex-tree doesn't understand all entities. The ones that have been figured out (the ones available in smaghetti), hex-tree knows their sizes because we figured them out. There are other entities where we think we know their size but aren't 100% sure. And there are still a lot of entities where we don't know their size at all.

In hex-tree, if you load star02, pretty much all objects and sprites load correctly because I have put a lot of effort into figuring out all the entities in that level. But if you load say mushroom20, hex-tree renders it as a total mess as it doesn't know the sizes of most of the entities in that level. As more entities are figured out, hex-tree will become more accurate. Hex-tree has tools in it that allow you to explore and figure out the sizes of entities, but it's a slow and tedious process.

When smaghetti is more mature, it will understand most or even all entities in the entire game. At that point, smaghetti would be able to load any e-reader level. But that is a long ways off.

**Comment by mariomadproductions** [comment]
Oh, so its not known how to produce .level files from e-Card (dumps) or from save files?

Ah, that's a bit of pain. It sounds like there is probably a table (or a load of if statements) in the code that determine what the different entities parameter lengths are.

**Comment by city41** [comment]
> It sounds like there is probably a table (or a load of if statements) in the code that determine what the different entities parameter lengths are.

Yeah there almost certainly is. I have no experience decompiling or debugging GBA games. But I am learning that stuff as well on the side. I'm hoping someone experienced with that might come along and pitch in. 

Gonna close this, as there's no actions to take.

**Comment by mariomadproductions** [comment]
Is there some other way I could contribute towards documenting object parameters?

**Comment by city41** [comment]
one way is to use hex-tree using localstorage. Here's how to do that.

1. Load up the editor in smaghetti: https://smaghetti.com/make
2. make a level
3. refresh the browser (this is what takes the level you just made and puts it in localstorage)
4. head to hex-tree: https://smaghetti.com/tools/hex-tree
5. click "start from localstorage"

the level you made in smaghetti will load into hex-tree. From there you can manipulate the level to try stuff. For example almost any byte can be changed by changing it, then clicking the upload button next to it.

![image](https://user-images.githubusercontent.com/141159/121062079-a9a13880-c792-11eb-8662-0bd0af272d3d.png)

keep in mind hex-tree is a very raw tool. I didn't really think anyone besides me would use it, I am gradually making it more user friendly.

**Comment by city41** [comment]
and as for what needs help, check the [discussions](https://github.com/city41/smaghetti/discussions) as well as the [issues](https://github.com/city41/smaghetti/issues). I am trying to keep everything up to date so no one does repeat work.

There is also the [wiki](https://github.com/city41/smaghetti/wiki)

**Comment by mariomadproductions** [comment]
Thanks, I'll have a go with hex tree using that method and have a look at those pages.
