### ISSUE TITLE
Solar Magic Advance has logic for getting sprite data lengths based on reverse engineering the game

### ISSUE THREAD

**Issue by mariomadproductions** [city41/smaghetti#70]
https://github.com/LuigiBlood/smagicadv/blob/master/Solar%20Magic%20Advance/Solar%20Magic%20Advance/Program.cs#L268

I was talking to LuigiBlood, as I was wondering how his tool dealt with sprite sizes. And he told me that he reversed engineered the game to find the logic that is used for the sprite data lengths. He reimplimented this in his editor (it doesn't access the game ROM to work it out). He said you can use re-use this code. He is happy for you to contact him to verify this. I hope this helps with getting sprites to work better.

**Comment by city41** [comment]
oh awesome, that is really cool! I'll look into adding this in this week

@LuigiBlood, does your code use an open source license?

**Comment by LuigiBlood** [comment]
It seems I didn't use an open license but it was entirely written from scratch so, I could just add a MIT License or something over it if you want.

**Comment by city41** [comment]
If you don't mind, that would be good. I know I'm being cautious, but rather safe than sorry.

And thanks for offering this! I'm going to take a closer look at the rest of solar magic's code and see if I can bring more learnings in

**Comment by city41** [comment]
awesome, thanks!

**Comment by city41** [comment]
I have a branch going with this change and I think some things might not be correct. I spot fixed a few sprite lengths. But then I came across this in mushroom22#room3

![image](https://user-images.githubusercontent.com/141159/121208359-00b51500-c848-11eb-9841-24a429593eb5.png)

the red ones are the tool saying they are probably wrong since the first byte is not 0 or 1. The one just above, bank 1, id 6d is the para-galoomba/bobomb generator, which has a length of 5 bytes. Playing that room in the emulator, there is indeed a para-galoomba generator. But since `id ^ (bank << 8)` is off the end of the table, the tool chose 4 bytes.

but overall this does seem like a good change. After the spot changes, I am finding just about all levels I've checked match Solar Magic Advance. I've got the original version 0.33.0.0, I don't believe this is the new one with the code on GitHub?

Not sure what to do about the above generator, so far it's the only one I've hit that is like that.

**Comment by city41** [comment]
and @LuigiBlood if you have input, awesome. but don't worry if you don't or don't have the time, we can work through this. thanks again!

**Comment by LuigiBlood** [comment]
To be honest it's maybe not a bank thing, I didn't figure every single possibility, just the logic that decides how many bytes it is.

**Comment by city41** [comment]
ok cool. I still think this is a good approach and I'm gonna keep pushing forward with it.

**Comment by LuigiBlood** [comment]
I honestly only suspect that both bytes are just a 16-bit big endian ID

**Comment by city41** [comment]
I've gotten that impression too. and it does make sense. 

but anyway, hex-tree's sprites are looking pretty darn accurate now for e-reader levels. might still have a few things to figure out, but overall headed in the right direction.

**Comment by city41** [comment]
These changes are now in at a38c9599f373b17d80027e454db66de302a8f6ec and they are also deployed.

I spot checked every e-reader level and hex-tree is now rendering a lot of levels surprisingly well.
